import create_consultor_stocks_table
import create_consultor_recommonds_trends_table
from stock.stockstoremgr import saveToDB

saveToDB()

create_consultor_stocks_table.doRun()

create_consultor_recommonds_trends_table.doRun()